---
ID: "a938c606-dfd6-40ac-b9c7-1f4a5b2823ff"
Parent: "afa5e5f4-bce6-44bb-96eb-17d2cda5efa7"
Template: "afa5e5f4-bce6-44bb-96eb-17d2cda5efa7"
Path: /sitecore/templates/Project/HCC Demo site collection/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241105T162240Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\HXXG3xnNRt
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\HXXG3xnNRt
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dcd015f5-f2a3-48fb-9f2c-e3f89624f46f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\HXXG3xnNRt
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241105T162240Z
