---
ID: "0d9b5ae1-b4ba-47b9-9075-54059cbe8ea7"
Parent: "ce71952e-5e2f-4155-bed9-9afb2b74ff2a"
Template: "ab987746-78b0-4773-a8de-b295c493b7a4"
Path: "/sitecore/content/HCC Demo site collection/hcc-demo-site-3/Settings/Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241113T183907Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "19893fef-5422-4178-b032-4c74107d5efd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241113T183907Z
